name: TravelGates
main: com.ghomerr.travelgates.TravelGates
version: 1.10.17 [1.6.2-R0.1]
author: Ghomerr
description: Set up some travel gates. A file "destinations.dat" is created to store data.
load: POSTWORLD
commands:
 travelgates:
  description: master command of this plugin
  aliases: tg