name: TravelGates
main: com.ghomerr.travelgates.TravelGates
version: 1.10.12 [1.4.7-R1.0]
author: Ghomerr
description: Set up some travel gates. A file "destinations.dat" is created to store data.
commands:
 travelgates:
  description: master command of this plugin
  aliases: tg